---Insertar datos hospitales
INSERT INTO hospitales (DIRECCION_HOSPITAL, NOMBRE_HOSPITAL)
SELECT DISTINCT 
    DIRECCION_HOSPITAL,
    NOMBRE_HOSPITAL
FROM tabla_temporal
WHERE DIRECCION_HOSPITAL IS NOT NULL AND NOMBRE_HOSPITAL IS NOT NULL;

-- Insertar datos victimas
INSERT INTO victimas(NOMBRE_VICTIMA, APELLIDO_VICTIMA, DIRECCION_VICTIMA, FECHA_MUERTE,
FECHA_PRIMERA_SOSPECHA , FECHA_CONFIRMACION, ESTATUS_ENFERMEDAD, HOSPITALES_ID_HOSPITAL)
SELECT DISTINCT
	tt.NOMBRE_VICTIMA,
	tt.APELLIDO_VICTIMA,
	tt.DIRECCION_VICTIMA,
	tt.FECHA_MUERTE,
	tt.FECHA_PRIMERA_SOSPECHA,
	tt.FECHA_CONFIRMACION,
	tt.ESTADO_VICTIMA,
	h.ID_HOSPITAL
FROM TABLA_TEMPORAL tt 
INNER JOIN HOSPITALES h ON tt.NOMBRE_HOSPITAL = h.NOMBRE_HOSPITAL  
WHERE tt.NOMBRE_VICTIMA IS NOT NULL AND tt.APELLIDO_VICTIMA IS NOT NULL;

--Insertar datos tratamiento
INSERT INTO TRATAMIENTOS (NOMBRE_TRATAMIENTO, EFECTIVIDAD)
SELECT DISTINCT 
TRATAMIENTO, 
EFECTIVIDAD 
FROM TABLA_TEMPORAL
WHERE TRATAMIENTO IS NOT NULL AND EFECTIVIDAD IS NOT NULL;


--Insertar datos TratamientosVictima

INSERT INTO TRATAMIENTOSVICTIMA(VICTIMAS_ID_VICTIMA, TRATAMIENTOS_ID_TRATAMIENTO, 
EFECTIVIDAD_EN_VICTIMA, FECHA_INICIO_TRATAMIENTO, FECHA_FIN_TRATAMIENTO)
SELECT DISTINCT 
v.ID_VICTIMA, 
t.ID_TRATAMIENTO,
tt.EFECTIVIDAD_EN_VICTIMA, 
tt.FECHA_INICIO_TRATAMIENTO,
tt.FECHA_FIN_TRATAMIENTO
FROM TABLA_TEMPORAL tt 
INNER JOIN VICTIMAS v ON v.NOMBRE_VICTIMA  = tt.NOMBRE_VICTIMA AND v.APELLIDO_VICTIMA = tt.APELLIDO_VICTIMA 
INNER JOIN TRATAMIENTOS t ON t.NOMBRE_TRATAMIENTO  = tt.TRATAMIENTO;

-- Insertar Ubicaciones 
INSERT INTO UBICACIONES(UBICACION, FECHA_LLEGADA, FECHA_SALIDA, VICTIMAS_ID_VICTIMA)
SELECT DISTINCT 
tt.UBICACION_VICTIMA, 
tt.FECHA_LLEGADA,
tt.FECHA_RETIRO,
v.ID_VICTIMA 
FROM TABLA_TEMPORAL tt 
INNER JOIN VICTIMAS v ON v.NOMBRE_VICTIMA = tt.NOMBRE_VICTIMA AND v.APELLIDO_VICTIMA = tt.APELLIDO_VICTIMA 
WHERE tt.UBICACION_VICTIMA IS NOT NULL;

--Insertar Allegados
INSERT INTO ALLEGADOS(NOMBRE, APELLIDOS)
SELECT DISTINCT 
tt.NOMBRE_ASOCIADO,
tt.APELLIDO_ASOCIADO
FROM TABLA_TEMPORAL tt 
WHERE tt.NOMBRE_ASOCIADO IS NOT NULL AND tt.APELLIDO_ASOCIADO IS NOT NULL;

--Insertar Victima Allegados 

INSERT INTO VICTIMAALLEGADOS(TIPO_CONTACTO, FECHA_CONOCIMIENTO,FECHA_INICIO_CONTACTO,
FECHA_FIN_CONTACTO, ALLEGADOS_ID_ASOCIADO, VICTIMAS_ID_VICTIMA)
SELECT DISTINCT 
tt.CONTACTO_FISICO,
tt.FECHA_CONOCIO,
tt.FECHA_INICIO_CONTACTO,
tt.FECHA_FIN_CONTACTO,
a.ID_ASOCIADO,
v.ID_VICTIMA
FROM TABLA_TEMPORAL tt 
INNER JOIN ALLEGADOS a ON a.NOMBRE = tt.NOMBRE_ASOCIADO AND a.APELLIDOS = tt.APELLIDO_ASOCIADO
INNER JOIN VICTIMAS v ON v.NOMBRE_VICTIMA = tt.NOMBRE_VICTIMA AND V.APELLIDO_VICTIMA = tt.APELLIDO_VICTIMA 
WHERE TT.CONTACTO_FISICO IS NOT NULL;












